### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by karneaud** [mtschirs/js-objectdetect#19]
Your framework is very well built. I'm using the framework on both video and images and while single faces are ok...when using multiple faces or videos i get a lot of false positives. 

is there a way to fine tune the detection ?

**Comment by mtschirs** [comment]
Hi karneaud,

there are several ways to reduce the number of false positives:

1. **Limit detector resolution:** Set the size of the canvas you want to perform detection on as small as possible (i.e. increase the minimum size of the faces you want to detect).

2. **Threshold by confidence value:** For each detected face, the detector returns an array [x, y, width, height, confidence]. The confidence is an integer starting from 1 indicating the number of nearby individual detections that have been grouped together into one result. You could eliminate detected faces with a confidence value below a certain threshold (see https://github.com/swozniak/googlifier for an example). The threshold could e.g. depend on detector canvas resolution and your stepsize.

3. **Separate detection from tracking:** E.g. use a high threshold to detect new faces and a low threshold to track a face that has already been detected (see file:///C:/Users/Martin/git/js-objectdetect/examples/example_gesture_input.htm). Bayesian filtering could come in handy to determine which detection at time step t+1 corresponds to an already confirmed detection at timestep t. Alternatively, use the camshift algorithm for tracking (see https://github.com/auduno/headtrackr for an implementation) once you have detected a new face with high confidence.

4. **Use skin color information:** Similar to the camshift algorithm, you could make use of color information (js-objectdetect runs on grayscale images only). Skin color can e.g. be defined as a specific range of RGB-values or inferred via histogram backprojection from an already detected face with high confidence value. See http://staff.eng.bahcesehir.edu.tr/~cigdemeroglu/papers/international_conference_papers/C_ICASSP2011.pdf for the simple but seemingly effective RGB based method, as well as the camshift algorithm mentioned above (which also shows you how to do histogram backprojection).

There are some additional parameters to tune, e.g. enable histogram equalization or make use of the canny edge detector and eliminate detections within regions of low edge density. While these functions are already builtin to the library, they are not available yet through the relatively simple detector interface since the performance or precision gain is usually low.
